# Generated by Django 4.1.3 on 2023-01-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0002_students_sem'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP_system',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('OTP', models.CharField(max_length=50)),
            ],
        ),
    ]
