# Generated by Django 4.1.3 on 2023-02-27 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0003_otp_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='fees_pay',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.CreateModel(
            name='payment_details',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_date', models.DateTimeField(auto_now=True)),
                ('amount_paid', models.CharField(default=None, max_length=50)),
                ('order_id', models.CharField(default=None, max_length=50)),
                ('courses_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management_app.courses')),
                ('sessionyear_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management_app.sessionyearmodel')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management_app.students')),
            ],
        ),
    ]
